name = "my-sveltekit-chatbot"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[pages]
build_output_dir = ".svelte-kit/cloudflare"
pages_build_output_dir = ".svelte-kit/cloudflare"  # Add this line
